import type {Metadata} from "next";
import "../styles/globals.scss";
import {Lato} from 'next/font/google';
import {storyblokInit, apiPlugin} from "@storyblok/react/rsc";
import StoryblokProvider from "@/components/StoryblokProvider/StoryblokProvider";
import QueryProvider from "@/components/QueryProvider/QueryProvider";

const lato = Lato({
    subsets: ['latin'],
    weight: ['300', '400', '700'],
    variable: '--font-lato',
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

storyblokInit({
    accessToken: process.env.STORYBLOK_TOKEN,
    use: [apiPlugin],
})

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <StoryblokProvider>
            <html lang="en" className={lato.variable}>
            <body className={lato.className}>
            <QueryProvider>
                {children}
            </QueryProvider>
            </body>
            </html>
        </StoryblokProvider>
    );
}
